service: pasleyhill
useDotenv: true

frameworkVersion: '3'

plugins:
  - serverless-domain-manager

package:
  patterns:
    - backend/**
    - '!.git/**'
    - '!.travis.yml'
  individually: true

params:
  default:
    baseDomain: ${self:service}.com
    domain: ${sls:stage}.${self:service}.com
    bucketName: ${sls:stage}.${self:service}.com
    certArn: arn:aws:acm:us-east-1:474597462976:certificate/a175f878-ffac-4db8-a4c9-8c14e69fcca5
    hostedZoneId: Z2FDTNDATAQYW2
    apiPrefix: ${sls:stage}-api
  prod:
    certArn: arn:aws:acm:us-east-1:474597462976:certificate/0c3922c8-7587-40c3-98ee-a82b4311273a
    domain: ${self:service}.com
    bucketName: ${self:service}.com
    apiPrefix: api

custom:
  customDomain:
    domainName: ${param:apiPrefix}.${param:baseDomain}
    basePath: ""
    certificateArn: ${param:certArn}
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: false
    hostedZoneId: Z09269873FNBE6HYXX020

provider:
  name: aws
  profile: pasley_hill_admin
  runtime: nodejs16.x
  httpApi:
    cors:
      allowedMethods:
        - OPTIONS
        - POST
        - GET
      allowedOrigins:
        - http://localhost:8080
        - http://localhost:8081
        - http://localhost:3001
        - http://localhost:3000
        - https://staging.pasleyhill.com
        - https://pasleyhill.com
        - https://www.pasleyhill.com
      allowedHeaders:
        - content-type
functions: 
  contact:
    handler: backend/main.handler
    environment:
      GOOGLE_RECAPTCHA_SECRET: ${env:GOOGLE_RECAPTCHA_SECRET}
    events:
      - httpApi:
          method: POST
          path: /contact

resources:
  Resources:
    ReadPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        Bucket: !Ref RootBucket
        PolicyDocument:
          Statement:
            - Action: 's3:GetObject'
              Effect: Allow
              Resource: 'arn:aws:s3:::${param:bucketName}/*'
              Principal: '*'
    CloudFrontOriginAccessIdentity:
      Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: !Ref RootBucket
    # Configure CloudFront
    CloudFrontDistribution:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          Aliases:
            - ${param:domain}
          DefaultRootObject: index.html
          ViewerCertificate:
            AcmCertificateArn: ${param:certArn}
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            AllowedMethods:
              - HEAD
              - DELETE
              - POST
              - GET
              - OPTIONS
              - PUT
              - PATCH
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            DefaultTTL: 100 # in seconds
            ForwardedValues:
              Cookies:
                Forward: none
              QueryString: false
            MaxTTL: 100 # in seconds
            MinTTL: 60 # in seconds
            TargetOriginId: s3origin
            ViewerProtocolPolicy: 'redirect-to-https'
          Enabled: true
          HttpVersion: http2
          Origins:
            - DomainName: !GetAtt 'RootBucket.DomainName'
              Id: s3origin
              S3OriginConfig:
                OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
          PriceClass: 'PriceClass_All'
    DnsRecord:
      Type: "AWS::Route53::RecordSet"
      Properties:
        AliasTarget:
          DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
          HostedZoneId: ${param:hostedZoneId}
        HostedZoneName: ${param:baseDomain}.
        Name: ${param:domain}
        Type: 'A'
    RootBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${param:bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html
    WWWBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: www.${param:bucketName}
        AccessControl: BucketOwnerFullControl
        WebsiteConfiguration:
          RedirectAllRequestsTo:
            HostName: !Ref RootBucket